import '../models/category.dart';
import '../models/supplier.dart';
import '../models/product.dart';
import '../models/inventory.dart';
import '../models/transaction.dart';

class DummyDataService {
  static List<Category> getDummyCategories() {
    final now = DateTime.now();
    return [
      Category(
        id: 1, 
        name: 'Pain Relief', 
        description: 'Medications for pain management',
        createdAt: now,
        updatedAt: now,
        productCount: 2,
      ),
      Category(
        id: 2, 
        name: 'Antibiotics', 
        description: 'Anti-bacterial medications',
        createdAt: now,
        updatedAt: now,
        productCount: 1,
      ),
      Category(
        id: 3, 
        name: 'Vitamins & Supplements', 
        description: 'Nutritional supplements',
        createdAt: now,
        updatedAt: now,
        productCount: 2,
      ),
      Category(
        id: 4, 
        name: 'First Aid', 
        description: 'Emergency medical supplies',
        createdAt: now,
        updatedAt: now,
        productCount: 1,
      ),
      Category(
        id: 5, 
        name: 'Prescription Drugs', 
        description: 'Prescription medications',
        createdAt: now,
        updatedAt: now,
        productCount: 2,
      ),
      Category(
        id: 6, 
        name: 'Personal Care', 
        description: 'Hygiene and personal care products',
        createdAt: now,
        updatedAt: now,
        productCount: 0,
      ),
      Category(
        id: 7, 
        name: 'Medical Devices', 
        description: 'Medical equipment and devices',
        createdAt: now,
        updatedAt: now,
        productCount: 1,
      ),
      Category(
        id: 8, 
        name: 'Baby Care', 
        description: 'Infant and baby care products',
        createdAt: now,
        updatedAt: now,
        productCount: 1,
      ),
    ];
  }

  static List<Supplier> getDummySuppliers() {
    final now = DateTime.now();
    return [
      Supplier(
        id: 1,
        name: 'MedPharm Solutions',
        contactPerson: 'Dr. Sarah Johnson',
        email: 'sarah@medpharm.com',
        phone: '+1-555-0123',
        address: '123 Medical Center Dr, Healthcare City, HC 12345',
        isActive: true,
        createdAt: now,
        updatedAt: now,
        productCount: 2,
      ),
      Supplier(
        id: 2,
        name: 'Global Pharmaceuticals',
        contactPerson: 'Michael Chen',
        email: 'mchen@globalpharma.com',
        phone: '+1-555-0456',
        address: '456 Pharma Ave, Business District, BD 67890',
        isActive: true,
        createdAt: now,
        updatedAt: now,
        productCount: 3,
      ),
      Supplier(
        id: 3,
        name: 'HealthCare Plus',
        contactPerson: 'Dr. Emily Rodriguez',
        email: 'emily@healthcareplus.com',
        phone: '+1-555-0789',
        address: '789 Wellness Blvd, Medical Park, MP 11111',
        isActive: true,
        createdAt: now,
        updatedAt: now,
        productCount: 2,
      ),
      Supplier(
        id: 4,
        name: 'VitaCorp Industries',
        contactPerson: 'James Wilson',
        email: 'jwilson@vitacorp.com',
        phone: '+1-555-0321',
        address: '321 Health Street, Wellness City, WC 22222',
        isActive: true,
        createdAt: now,
        updatedAt: now,
        productCount: 3,
      ),
    ];
  }

  static List<Product> getDummyProducts() {
    final now = DateTime.now();
    return [
      Product(
        id: 1,
        name: 'Acetaminophen 500mg',
        sku: 'ACET-500-001',
        description: 'Pain reliever and fever reducer',
        category: 1,
        categoryName: 'Pain Relief',
        supplier: 1,
        supplierName: 'MedPharm Solutions',
        unitPrice: 8.99,
        costPrice: 6.50,
        reorderLevel: 50,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 75,
        totalValue: 674.25,
        isLowStock: false,
      ),
      Product(
        id: 2,
        name: 'Ibuprofen 200mg',
        sku: 'IBUP-200-001',
        description: 'Anti-inflammatory pain medication',
        category: 1,
        categoryName: 'Pain Relief',
        supplier: 1,
        supplierName: 'MedPharm Solutions',
        unitPrice: 12.99,
        costPrice: 9.50,
        reorderLevel: 40,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 35,
        totalValue: 454.65,
        isLowStock: true,
      ),
      Product(
        id: 3,
        name: 'Amoxicillin 250mg',
        sku: 'AMOX-250-001',
        description: 'Broad-spectrum antibiotic',
        category: 2,
        categoryName: 'Antibiotics',
        supplier: 2,
        supplierName: 'Global Pharmaceuticals',
        unitPrice: 45.99,
        costPrice: 35.00,
        reorderLevel: 20,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 15,
        totalValue: 689.85,
        isLowStock: true,
      ),
      Product(
        id: 4,
        name: 'Vitamin D3 1000IU',
        sku: 'VITD-1000-001',
        description: 'Vitamin D supplement for bone health',
        category: 3,
        categoryName: 'Vitamins & Supplements',
        supplier: 4,
        supplierName: 'VitaCorp Industries',
        unitPrice: 15.99,
        costPrice: 12.00,
        reorderLevel: 30,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 120,
        totalValue: 1918.80,
        isLowStock: false,
      ),
      Product(
        id: 5,
        name: 'Band-Aid Assorted Sizes',
        sku: 'BAND-ASST-001',
        description: 'Adhesive bandages in various sizes',
        category: 4,
        categoryName: 'First Aid',
        supplier: 3,
        supplierName: 'HealthCare Plus',
        unitPrice: 6.99,
        costPrice: 4.50,
        reorderLevel: 100,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 85,
        totalValue: 594.15,
        isLowStock: false,
      ),
      Product(
        id: 6,
        name: 'Lisinopril 10mg',
        sku: 'LISI-10-001',
        description: 'ACE inhibitor for blood pressure',
        category: 5,
        categoryName: 'Prescription Drugs',
        supplier: 2,
        supplierName: 'Global Pharmaceuticals',
        unitPrice: 28.99,
        costPrice: 22.00,
        reorderLevel: 25,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 30,
        totalValue: 869.70,
        isLowStock: false,
      ),
      Product(
        id: 7,
        name: 'Blood Pressure Monitor',
        sku: 'BPM-001',
        description: 'Digital blood pressure monitoring device',
        category: 7,
        categoryName: 'Medical Devices',
        supplier: 3,
        supplierName: 'HealthCare Plus',
        unitPrice: 89.99,
        costPrice: 65.00,
        reorderLevel: 10,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 8,
        totalValue: 719.92,
        isLowStock: true,
      ),
      Product(
        id: 8,
        name: 'Baby Formula Premium',
        sku: 'BABY-FORM-001',
        description: 'Premium infant formula with DHA',
        category: 8,
        categoryName: 'Baby Care',
        supplier: 4,
        supplierName: 'VitaCorp Industries',
        unitPrice: 32.99,
        costPrice: 25.00,
        reorderLevel: 35,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 45,
        totalValue: 1484.55,
        isLowStock: false,
      ),
      Product(
        id: 9,
        name: 'Omeprazole 20mg',
        sku: 'OMEP-20-001',
        description: 'Proton pump inhibitor for acid reflux',
        category: 5,
        categoryName: 'Prescription Drugs',
        supplier: 2,
        supplierName: 'Global Pharmaceuticals',
        unitPrice: 35.99,
        costPrice: 28.00,
        reorderLevel: 30,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 25,
        totalValue: 899.75,
        isLowStock: true,
      ),
      Product(
        id: 10,
        name: 'Multivitamin Adult',
        sku: 'MULTI-ADULT-001',
        description: 'Complete daily multivitamin for adults',
        category: 3,
        categoryName: 'Vitamins & Supplements',
        supplier: 4,
        supplierName: 'VitaCorp Industries',
        unitPrice: 22.99,
        costPrice: 18.00,
        reorderLevel: 40,
        isActive: true,
        createdAt: now,
        updatedAt: now,
        currentStock: 60,
        totalValue: 1379.40,
        isLowStock: false,
      ),
    ];
  }

  static List<Inventory> getDummyInventory() {
    return [
      Inventory(
        id: 1,
        product: 1,
        productName: 'Acetaminophen 500mg',
        productSku: 'ACET-500-001',
        quantity: 75,
        unitPrice: 8.99,
        totalValue: 674.25,
        isLowStock: false,
        lastUpdated: DateTime.now().subtract(Duration(days: 2)),
      ),
      Inventory(
        id: 2,
        product: 2,
        productName: 'Ibuprofen 200mg',
        productSku: 'IBUP-200-001',
        quantity: 35,
        unitPrice: 12.99,
        totalValue: 454.65,
        isLowStock: true,
        lastUpdated: DateTime.now().subtract(Duration(days: 1)),
      ),
      Inventory(
        id: 3,
        product: 3,
        productName: 'Amoxicillin 250mg',
        productSku: 'AMOX-250-001',
        quantity: 15,
        unitPrice: 45.99,
        totalValue: 689.85,
        isLowStock: true,
        lastUpdated: DateTime.now().subtract(Duration(hours: 6)),
      ),
      Inventory(
        id: 4,
        product: 4,
        productName: 'Vitamin D3 1000IU',
        productSku: 'VITD-1000-001',
        quantity: 120,
        unitPrice: 15.99,
        totalValue: 1918.80,
        isLowStock: false,
        lastUpdated: DateTime.now().subtract(Duration(days: 3)),
      ),
      Inventory(
        id: 5,
        product: 5,
        productName: 'Band-Aid Assorted Sizes',
        productSku: 'BAND-ASST-001',
        quantity: 85,
        unitPrice: 6.99,
        totalValue: 594.15,
        isLowStock: false,
        lastUpdated: DateTime.now().subtract(Duration(hours: 12)),
      ),
      Inventory(
        id: 6,
        product: 6,
        productName: 'Lisinopril 10mg',
        productSku: 'LISI-10-001',
        quantity: 30,
        unitPrice: 28.99,
        totalValue: 869.70,
        isLowStock: false,
        lastUpdated: DateTime.now().subtract(Duration(days: 1)),
      ),
      Inventory(
        id: 7,
        product: 7,
        productName: 'Blood Pressure Monitor',
        productSku: 'BPM-001',
        quantity: 8,
        unitPrice: 89.99,
        totalValue: 719.92,
        isLowStock: true,
        lastUpdated: DateTime.now().subtract(Duration(days: 4)),
      ),
      Inventory(
        id: 8,
        product: 8,
        productName: 'Baby Formula Premium',
        productSku: 'BABY-FORM-001',
        quantity: 45,
        unitPrice: 32.99,
        totalValue: 1484.55,
        isLowStock: false,
        lastUpdated: DateTime.now().subtract(Duration(hours: 18)),
      ),
      Inventory(
        id: 9,
        product: 9,
        productName: 'Omeprazole 20mg',
        productSku: 'OMEP-20-001',
        quantity: 25,
        unitPrice: 35.99,
        totalValue: 899.75,
        isLowStock: true,
        lastUpdated: DateTime.now().subtract(Duration(days: 2)),
      ),
      Inventory(
        id: 10,
        product: 10,
        productName: 'Multivitamin Adult',
        productSku: 'MULTI-ADULT-001',
        quantity: 60,
        unitPrice: 22.99,
        totalValue: 1379.40,
        isLowStock: false,
        lastUpdated: DateTime.now().subtract(Duration(days: 1)),
      ),
    ];
  }

  static List<Transaction> getDummyTransactions() {
    return [
      Transaction(
        id: 1,
        product: 1,
        productName: 'Acetaminophen 500mg',
        productSku: 'ACET-500-001',
        transactionType: TransactionType.IN,
        transactionTypeDisplay: 'Stock In',
        quantity: 50,
        unitPrice: 8.99,
        reference: 'PO-001',
        notes: 'Restock from supplier',
        createdAt: DateTime.now().subtract(Duration(days: 2)),
      ),
      Transaction(
        id: 2,
        product: 2,
        productName: 'Ibuprofen 200mg',
        productSku: 'IBUP-200-001',
        transactionType: TransactionType.OUT,
        transactionTypeDisplay: 'Stock Out',
        quantity: 15,
        unitPrice: 12.99,
        reference: 'SALE-001',
        notes: 'Customer purchase',
        createdAt: DateTime.now().subtract(Duration(days: 1)),
      ),
      Transaction(
        id: 3,
        product: 3,
        productName: 'Amoxicillin 250mg',
        productSku: 'AMOX-250-001',
        transactionType: TransactionType.IN,
        transactionTypeDisplay: 'Stock In',
        quantity: 20,
        unitPrice: 45.99,
        reference: 'PO-002',
        notes: 'New shipment received',
        createdAt: DateTime.now().subtract(Duration(hours: 6)),
      ),
      Transaction(
        id: 4,
        product: 4,
        productName: 'Vitamin D3 1000IU',
        productSku: 'VITD-1000-001',
        transactionType: TransactionType.OUT,
        transactionTypeDisplay: 'Stock Out',
        quantity: 30,
        unitPrice: 15.99,
        reference: 'BULK-001',
        notes: 'Bulk order for local clinic',
        createdAt: DateTime.now().subtract(Duration(days: 3)),
      ),
      Transaction(
        id: 5,
        product: 5,
        productName: 'Band-Aid Assorted Sizes',
        productSku: 'BAND-ASST-001',
        transactionType: TransactionType.IN,
        transactionTypeDisplay: 'Stock In',
        quantity: 100,
        unitPrice: 6.99,
        reference: 'PO-003',
        notes: 'Restock first aid supplies',
        createdAt: DateTime.now().subtract(Duration(hours: 12)),
      ),
      Transaction(
        id: 6,
        product: 6,
        productName: 'Lisinopril 10mg',
        productSku: 'LISI-10-001',
        transactionType: TransactionType.OUT,
        transactionTypeDisplay: 'Stock Out',
        quantity: 5,
        unitPrice: 28.99,
        reference: 'RX-001',
        notes: 'Prescription filled',
        createdAt: DateTime.now().subtract(Duration(days: 1)),
      ),
      Transaction(
        id: 7,
        product: 7,
        productName: 'Blood Pressure Monitor',
        productSku: 'BPM-001',
        transactionType: TransactionType.OUT,
        transactionTypeDisplay: 'Stock Out',
        quantity: 2,
        unitPrice: 89.99,
        reference: 'SALE-002',
        notes: 'Medical device sale',
        createdAt: DateTime.now().subtract(Duration(days: 4)),
      ),
      Transaction(
        id: 8,
        product: 8,
        productName: 'Baby Formula Premium',
        productSku: 'BABY-FORM-001',
        transactionType: TransactionType.IN,
        transactionTypeDisplay: 'Stock In',
        quantity: 50,
        unitPrice: 32.99,
        reference: 'PO-004',
        notes: 'Baby care restock',
        createdAt: DateTime.now().subtract(Duration(hours: 18)),
      ),
      Transaction(
        id: 9,
        product: 9,
        productName: 'Omeprazole 20mg',
        productSku: 'OMEP-20-001',
        transactionType: TransactionType.OUT,
        transactionTypeDisplay: 'Stock Out',
        quantity: 10,
        unitPrice: 35.99,
        reference: 'RX-002',
        notes: 'Prescription medications',
        createdAt: DateTime.now().subtract(Duration(days: 2)),
      ),
      Transaction(
        id: 10,
        product: 10,
        productName: 'Multivitamin Adult',
        productSku: 'MULTI-ADULT-001',
        transactionType: TransactionType.IN,
        transactionTypeDisplay: 'Stock In',
        quantity: 40,
        unitPrice: 22.99,
        reference: 'PO-005',
        notes: 'Vitamin restock',
        createdAt: DateTime.now().subtract(Duration(days: 1)),
      ),
    ];
  }

  static Map<String, dynamic> getDummyStats() {
    return {
      'total_products': 10,
      'total_categories': 8,
      'total_suppliers': 4,
      'total_transactions': 10,
      'low_stock_items': 2,
      'out_of_stock_items': 0,
      'total_inventory_value': 15423.78,
      'monthly_revenue': 8794.88,
      'monthly_expenses': 6128.90,
    };
  }

  static Map<String, dynamic> getDummyInventorySummary() {
    return {
      'total_items': 502,
      'total_value': 15423.78,
      'low_stock_count': 2,
      'out_of_stock_count': 0,
      'categories_count': 8,
    };
  }

  static Map<String, dynamic> getDummyTransactionSummary() {
    return {
      'total_transactions': 10,
      'total_revenue': 8794.88,
      'total_expenses': 6128.90,
      'net_profit': 2665.98,
      'transactions_today': 3,
      'transactions_this_week': 8,
      'transactions_this_month': 10,
    };
  }
}
